site_name: EGR 314 Armando Botiller Datasheet
site_url: https://botilarm.github.io/
repo_url: https://github.com/botilarm/botilarm.github.io
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: custom_theme/
  palette:
    primary: green
    accent: white
  font:
    text: Arial
  logo: static/logo314.svg
  favicon: static/logo314.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow    
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - content.action.edit
    - navigation.footer
#    - navigation.sections
#    - navigation.expand
#    - navigation.instant # doesn't work that well

markdown_extensions:
  - attr_list #add attributes using curly brackets to images, see https://squidfunk.github.io/mkdocs-material/reference/images/
  - md_in_html # see https://squidfunk.github.io/mkdocs-material/reference/images/
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

draft_docs: |
  **/*_unpublished.md
  **/*_draft.md
  **/*_draft**
  
plugins:
  - search
  - glightbox # allow resize images, see https://squidfunk.github.io/mkdocs-material/reference/images/

extra_css:
  - stylesheets/extra.css  

extra_javascript:
 - javascripts/mathjax.js
 - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
nav:
  - Home: index.md
  - 01 Requirements: 01-Requirements/Requirements.md
  - 02 Block-Diagram: 02-Concept-Design/Design.md
  - 03 Component Selection: 03-Project-Requirements/Project-requirements.md
  - 04 BOM: 04-BOM/BOM.md
  - 05 Schematic: 05-Schematic/schematic.md
  - 06 PCB: 06-PCB/PCB.md
  - 07 API: 07-API/API.md
  - 08 Hardware V2.0: 08-Hardware-V2.0/Hardware-V2.0.md
  - 09 Resources: 09-Resources/Resources.md
  - 10 Reflection: 10-Reflection/Reflection.md

not_in_nav: |
  static
  
copyright: "Copyright &copy; 2026 Armando Botiller"

extra:
  generator: false
  social:
    - icon: fontawesome/regular/file-code
      link: /2026_spring
      name: 2023 Site    

